- name: Install html2text
  package:
    state: installed
    name: https://li.nux.ro/download/nux/dextop/el7/x86_64/html2text-1.3.2a-14.el7.nux.x86_64.rpm

- name: Get latest Filebeat version
  shell: curl -s -L https://www.elastic.co/downloads/elasticsearch  | html2text  | grep Version -A 1 | tail -1
  register: OUT

- name: Install filebeat
  package:
    name: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{OUT.stdout}}-x86_64.rpm
    state: installed

- name: Copy the /etc/filebeat/filebeat.yml
  template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml
  when: LOG_TEMPLATE is not defined

- name: Copy the /etc/filebeat/filebeat.yml
  template:
    src: node.yml
    dest: /etc/filebeat/filebeat.yml
  when: LOG_TEMPLATE is  defined

- name: Start filebeat service
  service:
    name: filebeat
    state: restarted


