- name: Create Application User
  user:
    name: "{{APPLICATION_USERNAME}}"

- name: Create Directory
  file:
    path: "{{APPLICATION_HOME}}"
    state: directory
    owner: "{{APPLICATION_USERNAME}}"
    group: "{{APPLICATION_USERNAME}}"


